// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sobranie.Infrastructure.Persistence;

#nullable disable

namespace Sobranie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SobranieDbContext))]
    [Migration("20260422005511_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Sobranie.Domain.BeefEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromMPId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ToMPId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromMPId", "ToMPId")
                        .IsUnique();

                    b.ToTable("BeefEdges");
                });

            modelBuilder.Entity("Sobranie.Domain.ChorusLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PartyId", "TopicTag");

                    b.ToTable("ChorusLines");
                });

            modelBuilder.Entity("Sobranie.Domain.LlmCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CalledAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("GenerationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrefillSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPreview")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rejected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt");

                    b.ToTable("LlmCallLogs");
                });

            modelBuilder.Entity("Sobranie.Domain.MPProfile", b =>
                {
                    b.Property<string>("MPId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Aggression")
                        .HasColumnType("REAL");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("Legalism")
                        .HasColumnType("REAL");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaSystemPrompt")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<double>("Populism")
                        .HasColumnType("REAL");

                    b.Property<int>("SeatIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("MPId");

                    b.HasIndex("PartyId");

                    b.HasIndex("Tier", "PartyId");

                    b.ToTable("MPs");
                });

            modelBuilder.Entity("Sobranie.Domain.Party", b =>
                {
                    b.Property<string>("PartyId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Sobranie.Domain.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("IntroducedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewrittenAsProposal")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt");

                    b.HasIndex("Status");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Sobranie.Domain.SignatureMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exemplar")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MPId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TriggerWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MPId");

                    b.ToTable("SignatureMoves");
                });

            modelBuilder.Entity("Sobranie.Domain.Speech", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<double>("GenerationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MPId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OutputFilterRejected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("UtilityAtSelection")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("UtteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.HasIndex("UtteredAt");

                    b.HasIndex("MPId", "UtteredAt");

                    b.ToTable("Speeches");
                });

            modelBuilder.Entity("Sobranie.Domain.ChorusLine", b =>
                {
                    b.HasOne("Sobranie.Domain.Party", "Party")
                        .WithMany("ChorusLines")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Sobranie.Domain.MPProfile", b =>
                {
                    b.HasOne("Sobranie.Domain.Party", "Party")
                        .WithMany("Members")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Sobranie.Domain.SignatureMove", b =>
                {
                    b.HasOne("Sobranie.Domain.MPProfile", "MP")
                        .WithMany("SignatureMoves")
                        .HasForeignKey("MPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MP");
                });

            modelBuilder.Entity("Sobranie.Domain.Speech", b =>
                {
                    b.HasOne("Sobranie.Domain.MPProfile", "MP")
                        .WithMany()
                        .HasForeignKey("MPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sobranie.Domain.Proposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalId");

                    b.Navigation("MP");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Sobranie.Domain.MPProfile", b =>
                {
                    b.Navigation("SignatureMoves");
                });

            modelBuilder.Entity("Sobranie.Domain.Party", b =>
                {
                    b.Navigation("ChorusLines");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
